version: '3.1'

services:
  postgres:
    image: postgres:9.6
    container_name: chameleon_postgres
    restart: always
    networks:
      - backend
      - frontend
    command: -p 9999
    ports:
      - '9999:9999'
    environment:
      POSTGRES_USER: changeme027a088931d22
      POSTGRES_PASSWORD: changeme0f40773877963
    logging:
        driver: none

networks:
  frontend:
    internal: false
  backend:
    internal: true
